### ISSUE TITLE
Potential XSS Vulnerability

### ISSUE THREAD

**Issue by Macavirus** [screencloud/app-core#40]
In PostMessageBridge, we do not test that the origin prop. matches what is expected. Theoretically an attacker could send arbitrary JS to execute in the listener window.

https://github.com/screencloud/app-core/blob/fb1d8766935ec0d30281fbdaa6dace5a99b382e1/src/PostMessageBridge.ts#L132-L136

Further, `this.target` is defined as:

https://github.com/screencloud/app-core/blob/fb1d8766935ec0d30281fbdaa6dace5a99b382e1/src/PostMessageBridge.ts#L47

Suggested resolution:
1. tighten up the initializer for targetWindow
2. 1. Use something like this to validate `event.origin` in addition to checking `event.source`.  (These domains may not be totally correct).
```
function validOrigin(origin) {
    const validPostMessageDomains = [
        "screen\.cloud",
        "screencloudapp\.com",
        "screencloud\.com",
        "screencloudapps\.com",
    ];
    const re = RegExp(`^https://(${validPostMessageDomains.join("|")})$`, "i")
    // Just for readability, written as an array and joined rather than one long regex
    // Be careful to escape every "."

    return re.test(origin)
}
```
@wmathes @michael-martin

**Comment by michael-martin** [comment]
@Macavirus The browser itself should verify the origin is correct, we shouldn't need to do it. At least, it does for child -> parent messages (The parent won't receive them if the child doesn't set this correctly)

Curious about your point on the child URL itself. I'm not sure how that origin property works. Is it set automatically, or can that be spoofed by the child?

If we can reliably do a comparison like you say, that sounds good to me. Instead of a list though, I'd compare to the expected player URL from the app's manifest. That way, we're all set for 3rd party apps as well (Where users might host it themselves)

**Comment by Macavirus** [comment]
most critical bits addressed by https://github.com/screencloud/auth-next-frontend/pull/155
